; MegaMan 2: Dr. Wilys Theme, AKG format, v1.0.

; Generated by Arkos Tracker 3.

    org 40960


Start
StartDisarkGenerateExternalLabel
DisarkByteRegionStart0
    db "AT30"
DisarkPointerRegionStart1
    dw ArpeggioTable    ; The address of the Arpeggio table.
    dw PitchTable    ; The address of the Pitch table.
    dw InstrumentTable    ; The address of the Instrument table.
    dw EffectBlockTable    ; The address of the Effect Block table.
DisarkPointerRegionEnd1


; The addresses of each Subsong.
DisarkPointerRegionStart2
    dw Subsong0_Start
DisarkPointerRegionEnd2

; Declares all the Arpeggios.
ArpeggioTable
DisarkPointerRegionStart3
DisarkPointerRegionEnd3

; Declares all the Pitches.
PitchTable
DisarkPointerRegionStart4
DisarkPointerRegionEnd4

; Declares all the Instruments.
InstrumentTable
DisarkPointerRegionStart5
    dw EmptyInstrument
    dw Instrument1
    dw Instrument2
    dw Instrument3
DisarkPointerRegionEnd5

EmptyInstrument
    db 0    ; The speed (>0, 0 for 256).

    db 0    ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

Instrument1
    db 4    ; The speed (>0, 0 for 256).

    db 241    ; Soft only. Volume: 14. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 6    ; Loop to silence.

Instrument2
    db 2    ; The speed (>0, 0 for 256).

Instrument2_Loop
    db 233    ; Soft only. Volume: 13. Volume only.

    db 7    ; Loop.
DisarkWordForceReference6
    dw Instrument2_Loop    ; Loop here.

Instrument3
    db 3    ; The speed (>0, 0 for 256).

    db 225    ; Soft only. Volume: 12. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 6    ; Loop to silence.


; The indexes of the effect blocks used by this song.
EffectBlockTable
DisarkPointerRegionStart7
    dw EffectBlock_P4P0    ; Index 0
    dw EffectBlock_P4P3    ; Index 1
    dw EffectBlock_P4P6    ; Index 2
    dw EffectBlock_P4P1    ; Index 3
    dw EffectBlock_P4P2    ; Index 4
    dw EffectBlock_P4P10    ; Index 5
    dw EffectBlock_P4P9    ; Index 6
    dw EffectBlock_P4P4    ; Index 7
    dw EffectBlock_P4P5    ; Index 8
    dw EffectBlock_P4P8    ; Index 9
DisarkPointerRegionEnd7
EffectBlock_P4P0
    db 4
    db 0

EffectBlock_P4P1
    db 4
    db 1

EffectBlock_P4P2
    db 4
    db 2

EffectBlock_P4P3
    db 4
    db 3

EffectBlock_P4P4
    db 4
    db 4

EffectBlock_P4P6
    db 4
    db 6

EffectBlock_P4P8
    db 4
    db 8

EffectBlock_P4P10
    db 4
    db 10

EffectBlock_P4P5
    db 4
    db 5

EffectBlock_P4P9
    db 4
    db 9


DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Subsong0_DisarkByteRegionStart0
Subsong0_Start
    db 2    ; ReplayFrequency (0=12.5hz, 1=25hz, 2=50hz, 3=100hz, 4=150hz, 5=300hz).
    db 2    ; Digichannel (>=0).
    db 1    ; PSG count (>0).
    db 0    ; Loop start index (>=0).
    db 8    ; End index (>=0).
    db 11    ; Initial speed (>=0).
    db 6    ; Base note index (>=0).

Subsong0_Linker
Subsong0_DisarkPointerRegionStart1
; Position 0
Subsong0_Linker_Loop
    dw Subsong0_Track0
    dw Subsong0_Track1
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 1
    dw Subsong0_Track0
    dw Subsong0_Track1
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock1
; Position 2
    dw Subsong0_Track3
    dw Subsong0_Track4
    dw Subsong0_Track5
    dw Subsong0_LinkerBlock2
; Position 3
    dw Subsong0_Track6
    dw Subsong0_Track7
    dw Subsong0_Track8
    dw Subsong0_LinkerBlock0
; Position 4
    dw Subsong0_Track9
    dw Subsong0_Track10
    dw Subsong0_Track11
    dw Subsong0_LinkerBlock0
; Position 5
    dw Subsong0_Track12
    dw Subsong0_Track13
    dw Subsong0_Track14
    dw Subsong0_LinkerBlock0
; Position 6
    dw Subsong0_Track6
    dw Subsong0_Track7
    dw Subsong0_Track8
    dw Subsong0_LinkerBlock3
; Position 7
    dw Subsong0_Track15
    dw Subsong0_Track16
    dw Subsong0_Track17
    dw Subsong0_LinkerBlock4
; Position 8
    dw Subsong0_Track18
    dw Subsong0_Track19
    dw Subsong0_Track20
    dw Subsong0_LinkerBlock0
Subsong0_DisarkPointerRegionEnd1
    dw 0    ; Loop.
Subsong0_DisarkWordForceReference2
    dw Subsong0_Linker_Loop

Subsong0_LinkerBlock0
    db 128    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
Subsong0_DisarkWordForceReference3
    dw Subsong0_SpeedTrack0    ; SpeedTrack address.
Subsong0_DisarkWordForceReference4
    dw Subsong0_EventTrack0    ; EventTrack address.

Subsong0_LinkerBlock1
    db 124    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
Subsong0_DisarkWordForceReference5
    dw Subsong0_SpeedTrack0    ; SpeedTrack address.
Subsong0_DisarkWordForceReference6
    dw Subsong0_EventTrack0    ; EventTrack address.

Subsong0_LinkerBlock2
    db 4    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
Subsong0_DisarkWordForceReference7
    dw Subsong0_SpeedTrack0    ; SpeedTrack address.
Subsong0_DisarkWordForceReference8
    dw Subsong0_EventTrack0    ; EventTrack address.

Subsong0_LinkerBlock3
    db 122    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
Subsong0_DisarkWordForceReference9
    dw Subsong0_SpeedTrack0    ; SpeedTrack address.
Subsong0_DisarkWordForceReference10
    dw Subsong0_EventTrack0    ; EventTrack address.

Subsong0_LinkerBlock4
    db 6    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
Subsong0_DisarkWordForceReference11
    dw Subsong0_SpeedTrack0    ; SpeedTrack address.
Subsong0_DisarkWordForceReference12
    dw Subsong0_EventTrack0    ; EventTrack address.


Subsong0_Track0
    db 223
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 34
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 31
    db 34
    db 60    ; Waits for 1 line.

    db 34
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 34
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 164
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 164
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 164
    db 1    ; New Instrument (1).
    db 36
    db 36
    db 60    ; Waits for 1 line.

    db 36
    db 36
    db 36
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 164
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 161
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 40
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 40
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 173
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 46
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track1
    db 192
    db 0    ; New Instrument (0).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 31
    db 31
    db 60    ; Waits for 1 line.

    db 31
    db 31
    db 31
    db 60    ; Waits for 1 line.

    db 26
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 154
    db 1    ; New Instrument (1).
    db 26
    db 31
    db 60    ; Waits for 1 line.

    db 31
    db 31
    db 31
    db 60    ; Waits for 1 line.

    db 26
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 31
    db 31
    db 60    ; Waits for 1 line.

    db 31
    db 31
    db 31
    db 60    ; Waits for 1 line.

    db 26
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 161
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 161
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 161
    db 1    ; New Instrument (1).
    db 33
    db 33
    db 60    ; Waits for 1 line.

    db 33
    db 33
    db 33
    db 60    ; Waits for 1 line.

    db 29
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 161
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 157
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 159
    db 1    ; New Instrument (1).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 31
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 40
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 40
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 43
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track2
    db 235
    db 3    ; New Instrument (3).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 41
    db 60    ; Waits for 1 line.

    db 43
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track3
    db 169
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 171
    db 2    ; New Instrument (2).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track4
    db 169
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 43
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track5
    db 169
    db 3    ; New Instrument (3).
    db 60    ; Waits for 1 line.

    db 43
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track6
    db 60    ; Waits for 1 line.

    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 233
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 34
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 169
    db 2    ; New Instrument (2).
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 105
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 43
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 102
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 39
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 105
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 46
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 233
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 42
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 170
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 42
    db 60    ; Waits for 1 line.

    db 45
    db 60    ; Waits for 1 line.

    db 50
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track7
    db 60    ; Waits for 1 line.

    db 171
    db 2    ; New Instrument (2).
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 7    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 105
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 34
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 169
    db 2    ; New Instrument (2).
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 105
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 43
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 102
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 39
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 43
    db 60    ; Waits for 1 line.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 124    ; No note, but effects.
    db 7    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 124    ; No note, but effects.
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 124    ; No note, but effects.
    db 9    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 124    ; No note, but effects.
    db 5    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 105
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 46
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 8    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 233
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 42
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 170
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 42
    db 60    ; Waits for 1 line.

    db 45
    db 60    ; Waits for 1 line.

    db 178
    db 2    ; New Instrument (2).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track8
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 172
    db 3    ; New Instrument (3).
    db 44
    db 44
    db 60    ; Waits for 1 line.

    db 44
    db 44
    db 44
    db 60    ; Waits for 1 line.

    db 51
    db 51
    db 48
    db 48
    db 48
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 44
    db 44
    db 51
    db 60    ; Waits for 1 line.

    db 48
    db 48
    db 55
    db 60    ; Waits for 1 line.

    db 48
    db 48
    db 51
    db 60    ; Waits for 1 line.

    db 44
    db 44
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 50
    db 50
    db 46
    db 46
    db 53
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 43
    db 46
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 53
    db 60    ; Waits for 1 line.

    db 46
    db 46
    db 50
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 44
    db 60    ; Waits for 1 line.

    db 44
    db 44
    db 44
    db 60    ; Waits for 1 line.

    db 44
    db 44
    db 44
    db 60    ; Waits for 1 line.

    db 51
    db 51
    db 48
    db 48
    db 48
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 44
    db 44
    db 51
    db 60    ; Waits for 1 line.

    db 48
    db 48
    db 55
    db 60    ; Waits for 1 line.

    db 48
    db 48
    db 51
    db 60    ; Waits for 1 line.

    db 44
    db 44
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 42
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 42
    db 60    ; Waits for 1 line.

    db 42
    db 60    ; Waits for 1 line.

    db 42
    db 60    ; Waits for 1 line.

    db 42
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 128
    db 0    ; New Instrument (0).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track9
    db 218
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 2    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 88
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 29
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 27
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 26
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 27
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 26
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 2    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 6    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 29
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 27
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 26
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 27
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 22
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 86
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 24
    db 60    ; Waits for 1 line.

    db 26
    db 60    ; Waits for 1 line.

    db 21
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 2    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 6    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 223
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 168
    db 2    ; New Instrument (2).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 223
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 40
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 169
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 171
    db 2    ; New Instrument (2).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track10
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 162
    db 1    ; New Instrument (1).
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 34
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 31
    db 34
    db 60    ; Waits for 1 line.

    db 34
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 34
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 164
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 164
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 164
    db 1    ; New Instrument (1).
    db 36
    db 36
    db 60    ; Waits for 1 line.

    db 36
    db 36
    db 36
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 164
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 161
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 159
    db 1    ; New Instrument (1).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 31
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 168
    db 2    ; New Instrument (2).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 223
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 40
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 50
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track11
    db 173
    db 3    ; New Instrument (3).
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 41
    db 60    ; Waits for 1 line.

    db 43
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track12
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 235
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 60    ; Waits for 1 line.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 46
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 114
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 46
    db 60    ; Waits for 1 line.

    db 45
    db 60    ; Waits for 1 line.

    db 43
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 107
    db 0    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 60    ; Waits for 1 line.

    db 43
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 174
    db 2    ; New Instrument (2).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 110
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 46
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 45
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 109
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 50
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 112
    db 0    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 46
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 45
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 45
    db 60    ; Waits for 1 line.

    db 46
    db 60    ; Waits for 1 line.

    db 45
    db 60    ; Waits for 1 line.

    db 43
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 223
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 40
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 169
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 171
    db 2    ; New Instrument (2).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track13
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 162
    db 1    ; New Instrument (1).
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 34
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 31
    db 34
    db 60    ; Waits for 1 line.

    db 34
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 34
    db 34
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 164
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 164
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 164
    db 1    ; New Instrument (1).
    db 36
    db 36
    db 60    ; Waits for 1 line.

    db 36
    db 36
    db 36
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 164
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 161
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 168
    db 2    ; New Instrument (2).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 223
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 41
    db 60    ; Waits for 1 line.

    db 40
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 50
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track14
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 171
    db 3    ; New Instrument (3).
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 43
    db 60    ; Waits for 1 line.

    db 43
    db 43
    db 41
    db 60    ; Waits for 1 line.

    db 43
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track15
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 162
    db 2    ; New Instrument (2).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track16
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 159
    db 2    ; New Instrument (2).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track17
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 167
    db 3    ; New Instrument (3).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track18
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 162
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 34
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 60    ; Waits for 1 line.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 39
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 38
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 36
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 36
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 164
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 38
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 166
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 164
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 34
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 60    ; Waits for 1 line.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 39
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 38
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 36
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 161
    db 2    ; New Instrument (2).
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 31
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 2    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 5    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track19
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 29
    db 60    ; Waits for 1 line.

    db 31
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 39
    db 60    ; Waits for 1 line.

    db 36
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 36
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 34
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 33
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 33
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 161
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 161
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 162
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 161
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 159
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 29
    db 60    ; Waits for 1 line.

    db 31
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 39
    db 60    ; Waits for 1 line.

    db 36
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 36
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 34
    db 61
    db 6    ; Waits for 7 lines.

    db 128
    db 0    ; New Instrument (0).
    db 60    ; Waits for 1 line.

    db 157
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 29
    db 60    ; Waits for 1 line.

    db 154
    db 2    ; New Instrument (2).
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 2    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 5    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 128
    db 0    ; New Instrument (0).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track20
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 167
    db 3    ; New Instrument (3).
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 31
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 45
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 46
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 31
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 33
    db 60    ; Waits for 1 line.

    db 45
    db 60    ; Waits for 1 line.

    db 34
    db 60    ; Waits for 1 line.

    db 46
    db 60    ; Waits for 1 line.

    db 33
    db 60    ; Waits for 1 line.

    db 39
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 39
    db 39
    db 39
    db 60    ; Waits for 1 line.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 41
    db 60    ; Waits for 1 line.

    db 41
    db 41
    db 42
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 43
    db 61
    db 10    ; Waits for 11 lines.

    db 41
    db 60    ; Waits for 1 line.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 60    ; Waits for 1 line.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 41
    db 60    ; Waits for 1 line.

    db 42
    db 60    ; Waits for 1 line.

    db 43
    db 61
    db 127    ; Waits for 128 lines.


; The speed tracks
Subsong0_SpeedTrack0
    db 255    ; Wait for 128 lines.

; The event tracks
Subsong0_EventTrack0
    db 255    ; Wait for 128 lines.

Subsong0_DisarkByteRegionEnd0
